### ISSUE TITLE
Sample event

### ISSUE THREAD

**Issue by sandyclouduser** [marekq/serverless-cognito#2]
Hi @marekq , I'm pretty new to cogntio. I'm trying to achieve a Server-side authentication using cogntio-apigateway-lambda. Could you kindly provided a sample event to test the app, it will help me to figure out the sequence of events.

**Comment by marekq** [comment]
Thanks, there is an event.json file included now which will allow you to run `sam local invoke -e event.json` on your machine. Once you deploy the SAM app, you can visit the URL of your app from the CloudFormation output overview. 

Please ping me if I can help you any further, I promise to reply faster this time... :-)
